channels:
  - conda-forge
  - usgs-astrogeology

dependencies:
  - cmake
  - cpp-filesystem
  - cxx-compiler
  - doxygen
  - ninja
  - pip
  - pytest
  - python
  - swig
  - spdlog
  - numpy
  - pip:
    - mkdocs
    - mkdoxy
    - mkdocs-material
